name: Add or update URL

on:
  workflow_dispatch:
    inputs:
      path:
        description: "Path part of the shortened URL"
        required: true
        type: string
      url:
        description: 'URL to shorten. Type "delete" to remove URL.'
        required: true
        type: string
      override:
        description: "Override (or delete) the URL mapping if it exists. Will throw an error otherwise."
        required: false
        type: boolean

jobs:
  edit:
    runs-on: ubuntu-latest
    name: Redirect ${{ inputs.path }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update config
        run: |
          python3 validate_and_add.py "${{ inputs.path }}" "${{ inputs.url }}" --override ${{ inputs.override }}
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git "add vercel.json" \
          git commit -m 's: edit "${{ inputs.path }}" redirect'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
